spring.application.name=upgrader-service

# LIS-SKINS
lisskins.api.key=${LISSKINS_API_KEY}

# Steam
steam.api.key=${STEAM_API_KEY}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration.ms=${JWT_EXPIRATION_MS:86400000}

# Frontend
app.frontend.url=${APP_FRONTEND_URL:http://localhost:5174}

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/upgrader}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:upgrader}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:upgrader}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

spring.flyway.enabled=true

# Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

# Swagger
springdoc.swagger-ui.path=/swagger